### ISSUE TITLE
Can't build cl-wave-writer-make-readme

### ISSUE THREAD

**Issue by quicklisp** [Frechmatz/cl-wave-file-writer#1]
Where can I find the cl-readme project?

**Comment by Frechmatz** [comment]
Hi there, the cl-readme project can be found here: https://github.com/Frechmatz/cl-readme
It is a library of mine which provides tooling for the generation of documentation. It is not yet ready for prime time and therefore not available via Quicklisp.
In order to build cl-wave-file-writer-make-readme the cl-readme project needs to be manually cloned into the local-projects directory of the Quicklisp installation.

**Comment by Frechmatz** [comment]
Hi Zach, thank you for the December update. I've updated the "quickload-current-release" branch of the project, in order to use the recently released cl-html-readme project instead of cl-readme. 

I've also reworked the ASD system definitions. Instead of multiple ASD files there is now only one ASD file cl-wave-file-writer.asd which defines the systems "cl-wave-file-writer" and "cl-wave-file-writer/doc".

Please come back to me in case of any questions or problems.

Thanks,
Oliver
